$ErrorActionPreference = "Stop"

function Apply-Replacements($path, $pairs) {
    $text = Get-Content -Raw -Encoding UTF8 $path
    foreach ($pair in $pairs) {
        $text = $text.Replace($pair[0], $pair[1])
    }
    Set-Content -Encoding UTF8 $path $text
}

$base = 'C:\Users\Balint\Documents\Pet_projects\zerve\zerve_hackathon_fixed_v2'

Apply-Replacements (Join-Path $base '04_cohort_analysis.py') @(
    @(' 04_cohort_analysis.py  --  Kohorsz Elemzés', ' 04_cohort_analysis.py  --  Cohort Analysis'),
    @('  A) Signup hónap szerinti kohorsz', '  A) Signup month-based cohort'),
    @('     -- Melyik hónapban regisztráltak?', '     -- Which month did users register in?'),
    @('     -- Hogyan fejlődött a platform user-bázisa?', '     -- How did the platform user base evolve?'),
    @('     -- Melyik kohorsz lett a legelkötelezettebbé?', '     -- Which cohort became the most engaged?'),
    @('  B) Agent adoptáció időzítése szerinti kohorsz', '  B) Cohort by agent adoption timing'),
    @('     -- Korai adoptálók (<1h signup után)', '     -- Early adopters (<1h after signup)'),
    @('     -- Késői adoptálók (1h+)', '     -- Late adopters (1h+)'),
    @('     -- Soha nem adoptálók', '     -- Never adopters'),
    @('     Ez KULONALLO a signup kohorsz elemzéstől!', '     This is SEPARATE from the signup cohort analysis!'),
    @('print("\n-- A) Signup Kohorsz Elemzés --")', 'print("\n-- A) Signup Cohort Analysis --")'),
    @('# A1. Kohorsz méret és engagement', '# A1. Cohort size and engagement'),
    @('"Regisztrálók száma kohorszonként"', '"Number of registrants by cohort"'),
    @('"Agent adoptáció aránya (%)"', '"Agent adoption rate (%)"'),
    @('"Átlag agent tool hívás / user"', '"Average agent tool calls / user"'),
    @('# A2. Szegmens összetétel kohorszonként', '# A2. Segment composition by cohort'),
    @('# A3. Engagement metrikák kohorszonként -- line chart', '# A3. Engagement metrics by cohort -- line chart'),
    @('name="Agent adoptáció %"', 'name="Agent adoption %"'),
    @('title_text="Agent adoptáció %"', 'title_text="Agent adoption %"'),
    @('print("\n-- B) Agent Adoptáció Kohorsz Elemzés --")', 'print("\n-- B) Agent Adoption Cohort Analysis --")'),
    @('print("   (Ez NEM a signup kohorsz -- ez a viselkedés alapján képzett csoport)")', 'print("   (This is NOT the signup cohort -- this is a behavior-based group)")'),
    @('# B1. Adoptáció kohorsz összehasonlítás', '# B1. Adoption cohort comparison'),
    @('# Normalizálás a max-hoz', '# Normalize to the max'),
    @('# B2. Adoptáció kohorsz x signup kohorsz kereszttábla', '# B2. Adoption cohort x signup cohort cross-tab'),
    @('# B3. Bar comparison -- kulcs metrikák adoptáció szerint', '# B3. Bar comparison -- key metrics by adoption timing'),
    @('title="Korai vs Késői vs Soha Agent Adoptáló -- Kulcs Metrikák<br>"', 'title="Early vs Late vs Never Agent Adopter -- Key Metrics<br>"'),
    @('"<sup>A korai adoptálók lényegesen elkötelezettebb felhasználókká váltak?</sup>"', '"<sup>Did early adopters become substantially more engaged users?</sup>"'),
    @('(adoption_cohort hozzáadva)', '(adoption_cohort added)'),
    @('Signup kohorsz elemzés: 3 chart', 'Signup cohort analysis: 3 charts'),
    @('Agent adoptáció kohorsz: 3 chart', 'Agent adoption cohort: 3 charts'),
    @('Kohorsz Elemz', 'Cohort Analysis'),
    @('KET KULONALLO KOHORSZ ELEMZES:', 'TWO SEPARATE COHORT ANALYSES:'),
    @('Melyik kohorsz lett a legelk', 'Which cohort became the most engaged?'),
    @('Ez KULONALLO a signup kohorsz elemz', 'This is SEPARATE from the signup cohort analysis!'),
    @('SIGNUP HONAP KOHORSZ ELEMZES', 'SIGNUP MONTH COHORT ANALYSIS'),
    @('Signup Kohorsz Elemz', 'Signup Cohort Analysis'),
    @('Kohorsz m', 'Cohort size and engagement'),
    @('Regisztr', 'Number of registrants by cohort'),
    @('Agent adopt', 'Agent adoption'),
    @('tlag agent tool h', 'Average agent tool calls / user'),
    @('Szegmens ', 'Segment composition by cohort'),
    @('Engagement metrik', 'Engagement metrics by cohort'),
    @('AGENT ADOPTACIO KOHORSZ -- KULONALLO ELEMZES', 'AGENT ADOPTION COHORT -- SEPARATE ANALYSIS'),
    @('viselked', 'behavior'),
    @('Adopt', 'Adoption'),
    @('Normaliz', 'Normalize'),
    @('kulcs metrik', 'key metrics'),
    @('-- MENTES -----------------------------------------------', '-- SAVE -----------------------------------------------'),
    @('hozz', 'added'),
    @('Fontos: a KET elemzes ortogonalis -- kulonvalasztas!', 'Important: the TWO analyses are orthogonal and intentionally separated!')
)

Apply-Replacements (Join-Path $base '05_lifecycle_analysis.py') @(
    @(' 05_lifecycle_analysis.py  --  Életút & Konverzió Elemzés', ' 05_lifecycle_analysis.py  --  Lifecycle & Conversion Analysis'),
    @('Két elemzés:', 'Two analyses:'),
    @('  A) Életút -- mikor lépett be az agent használatba?', '  A) Lifecycle -- when did agent usage begin?'),
    @('     Mennyi idő telt el signup és első agent tool közt?', '     How much time passed between signup and the first agent tool?'),
    @('     Milyen gyorsan "mélyülnek el" a userek?', '     How quickly do users deepen their usage?'),
    @('  B) Konverzió funnel -- szegmensenként és kohorszonként', '  B) Conversion funnel -- by segment and cohort'),
    @('     Hány user jutott el sign_up -> run -> agent -> build?', '     How many users reached sign_up -> run -> agent -> build?'),
    @('print("\n-- A) Életút Elemzés --")', 'print("\n-- A) Lifecycle Analysis --")'),
    @('# A1. Time-to-first-action eloszlás szegmensenként', '# A1. Time-to-first-action distribution by segment'),
    @('"<sup>Max 1440 perc (24h) -- csak aktív userek</sup>"', '"<sup>Max 1440 minutes (24h) -- active users only</sup>"'),
    @('# A2. Agent adoptáció időzítése', '# A2. Agent adoption timing'),
    @('labels = ["<15 perc", "15-60 perc", "1-4 óra", "4-24 óra", "1-7 nap"]', 'labels = ["<15 min", "15-60 min", "1-4 hours", "4-24 hours", "1-7 days"]'),
    @('"<sup>Csak az agent-et valaha használó userek</sup>"', '"<sup>Only users who ever used the agent</sup>"'),
    @('# A3. Aktív napok eloszlása szegmensenként (tenure)', '# A3. Active days distribution by segment (tenure)'),
    @('title="Active days distribution by segment<br><sup>Max 30 nap -- who returns regularly?</sup>"', 'title="Active days distribution by segment<br><sup>Max 30 days -- who returns regularly?</sup>"'),
    @('print("\n-- B) Konverzió Funnel Elemzés --")', 'print("\n-- B) Conversion Funnel Analysis --")'),
    @('# Funnel lépések a feature mátrixból', '# Funnel steps from the feature matrix'),
    @('# Globális funnel', '# Global funnel'),
    @('# Funnel kohorszonként', '# Funnel by cohort'),
    @('print("\n  Funnel signup kohorszonként:")', 'print("\n  Funnel by signup cohort:")'),
    @('# Újraértékeljük a feltételt a csoportra', '# Re-evaluate the condition for the group'),
    @('# Egyszerűbb: aggregált metrikák', '# Simpler: aggregated metrics'),
    @('# Konverzió % az első lépéshez képest', '# Conversion % relative to the first step'),
    @('"<sup>Javul a platform konverziója az újabb kohorszoknál?</sup>"', '"<sup>Is platform conversion improving for newer cohorts?</sup>"'),
    @('yaxis_title="Konverzió % (regisztráltakhoz képest)"', 'yaxis_title="Conversion % (relative to registrants)"'),
    @('# B3. Drop-off elemzés -- hol vesznek el a userek?', '# B3. Drop-off analysis -- where are users lost?'),
    @('"<sup>A teljes regisztrált bázishoz képest</sup>"', '"<sup>Relative to the full registered user base</sup>"'),
    @('print(f"  Életút: {OUTPUT_DIR}/05_ttf_distribution.html")', 'print(f"  Lifecycle: {OUTPUT_DIR}/05_ttf_distribution.html")'),
    @('print(f"  Konverzió funnel: {OUTPUT_DIR}/05_global_funnel.html")', 'print(f"  Conversion funnel: {OUTPUT_DIR}/05_global_funnel.html")'),
    @('Konverzi', 'Conversion'),
    @('Eletut', 'Lifecycle'),
    @('K', 'Two analyses:'),
    @('eloszl', 'distribution'),
    @('Max 1440 perc (24h) -- csak akt', 'Max 1440 minutes (24h) -- active users only'),
    @('<15 perc', '<15 min'),
    @('15-60 perc', '15-60 min'),
    @('1-7 nap', '1-7 days'),
    @('Akt', 'Active'),
    @('Max 30 nap --', 'Max 30 days --'),
    @('Funnel l', 'Funnel steps from the feature matrix'),
    @('Glob', 'Global'),
    @('jra', 'Re-evaluate'),
    @('Egyszer', 'Simpler'),
    @('atlepett', 'transition'),
    @('elveszett', 'lost'),
    @('Életút:', 'Lifecycle:'),
    @('Konverzi', 'Conversion')
)

Apply-Replacements (Join-Path $base '06_kpi_and_modeling.py') @(
    @(' 06_kpi_and_modeling.py  --  KPI Számítás & Modellezés', ' 06_kpi_and_modeling.py  --  KPI Calculation & Modeling'),
    @('KPI-ok szegmens x kohorsz mátrixban, majd ML modell', 'KPIs in a segment x cohort matrix, followed by an ML model'),
    @('ami megjósolja hogy egy user Agent Builder/Runner lesz-e', 'that predicts whether a user will become an Agent Builder/Runner'),
    @('(= a "siker" definíció, ami most már adatalapú).', '(= the definition of "success", now data-driven).'),
    @('print("\n-- A) KPI Mátrix --")', 'print("\n-- A) KPI Matrix --")'),
    @('# Normalizálás soronként', '# Normalization by column'),
    @('# Tényleges értékek annotációként', '# Actual values as annotations'),
    @('# KPI kohorszonként is', '# KPIs by cohort as well'),
    @('print("\n-- KPI kohorszonként --")', 'print("\n-- KPIs by cohort --")'),
    @('# Korai jelzok -- az elso nap utan merheto viselkedés', '# Early signals -- behavior measurable after the first day'),
    @('# es a ttf_agent_* -ot helyettesitjuk a relatív idővel', '# and replace ttf_agent_* with relative timing'),
    @('"signup_hour"              : "Napszak hatassal van az elkotelezodésre",', '"signup_hour"              : "Time of day influences engagement",'),
    @('KPI Sz', 'KPI Calculation & Modeling'),
    @('megj', 'predicts'),
    @('siker', 'success'),
    @('KPI M', 'KPI Matrix'),
    @('Normaliz', 'Normalization'),
    @('T', 'Actual'),
    @('kohorszonk', 'by cohort'),
    @('MODELLEZES -- KET SZINT', 'MODELING -- TWO LEVELS'),
    @('TELJES POPULACIO', 'FULL POPULATION'),
    @('SZUKITETT', 'NARROWED'),
    @('Modellezes', 'Modeling'),
    @('Korai jelzok', 'Early signals'),
    @('Uj feature-ok', 'New features'),
    @('Referrer one-hot oszlopok', 'Referrer one-hot columns'),
    @('Teljes populacio', 'Full population'),
    @('Szukitett', 'Narrowed'),
    @('Kerdes', 'Question'),
    @('Tobbi agent user', 'Other agent users'),
    @('relat', 'relative'),
    @('csak 1 osztaly', 'only 1 class'),
    @('Modellek mentve', 'Models saved')
)

Apply-Replacements (Join-Path $base '07_signup_hour_survival.py') @(
    @('   -- Szegmensenként és adoptáció szerint', '   -- By segment and adoption timing'),
    @('print("\n  Oranként Agent Builder % (top 5 ora):")', 'print("\n  Agent Builder % by hour (top 5 hours):")'),
    @('"Agent Builder % oranként (UTC -- India +5:30, US -5/-8)"', '"Agent Builder % by hour (UTC -- India +5:30, US -5/-8)"'),
    @('"Ghost % oranként"', '"Ghost % by hour"'),
    @('# Chart 2: Orasav kategoria összehasonlitas', '# Chart 2: Time-window category comparison'),
    @('print("\n  Orasav kategoria összehasonlitas:")', 'print("\n  Time-window category comparison:")'),
    @('"<sup>Melyik napszakban regisztrálnak az elkötelezett userek?</sup>"', '"<sup>Which time of day brings in the most engaged users?</sup>"'),
    @('# Chart 3: Hetvege vs hétköznap', '# Chart 3: Weekend vs weekday'),
    @('print("\n  Hétköznap vs Hétvége:")', 'print("\n  Weekday vs Weekend:")'),
    @('# - "ido" = days_active (hány különböző napon volt aktív)', '# - "time" = days_active (how many distinct days they were active)'),
    @('# - Megkerdés: ki marad aktív legalabb N napon?', '# - Question: who stays active for at least N days?'),
    @('# -- B1. Kaplan-Meier szegmensenként --', '# -- B1. Kaplan-Meier by segment --'),
    @('"<sup>Kaplan-Meier: P(aktív marad legalabb N napon) szegmensenként</sup>"', '"<sup>Kaplan-Meier: P(staying active for at least N days) by segment</sup>"'),
    @('"<sup>Aki 24 órán belül visszajön vs. aki kesobb vs. aki soha</sup>"', '"<sup>Users returning within 24 hours vs later vs never</sup>"'),
    @('# -- B4. time_to_return_hours kuszob elemzés --', '# -- B4. time_to_return_hours threshold analysis --'),
    @('print("\n  Visszaterest kuszob elemzés (Agent Builder % early vs late):")', 'print("\n  Return threshold analysis (Agent Builder % early vs late):")'),
    @('"<sup>Agent Builder % azon usereknel akik <= N orán belül visszajottek</sup>"', '"<sup>Agent Builder % among users who returned within <= N hours</sup>"'),
    @('# Fallback: egyszerű bar chart survival helyett', '# Fallback: simple bar chart instead of survival'),
    @('KET ELEMZES:', 'TWO ANALYSES:'),
    @('SIGNUP HOUR ELEMZES', 'SIGNUP HOUR ANALYSIS'),
    @('Elemzes', 'Analysis'),
    @('Userek', 'Users'),
    @('Orank', 'Hourly Agent Builder %'),
    @('Orasav', 'Time-window'),
    @('Visszateres', 'Return'),
    @('Hetvege', 'Weekend'),
    @('Survival definicio:', 'Survival definition:'),
    @('Megkerd', 'Question'),
    @('legalabb', 'at least'),
    @('Kaplan-Meier szegmensenk', 'Kaplan-Meier by segment'),
    @('keso', 'late'),
    @('kuszob', 'threshold'),
    @('lifelines nincs telepitve -- pip install lifelines', 'lifelines is not installed -- pip install lifelines'),
    @('atugrorva', 'skipped')
)

Apply-Replacements (Join-Path $base '08_india_hypothesis_success_def.py') @(
    @('   -- UTC 0-6h regisztrálók valóban indiaiak-e?', '   -- Are UTC 0-6h registrants really from India?'),
    @('   -- Miert nem onkényes a hatar (>= 3 build call)', '   -- Why the threshold is not arbitrary (>= 3 build calls)'),
    @('   -- Uzleti ertek: kredit tullépés, multi-day retention', '   -- Business value: credit overage, multi-day retention'),
    @('# UTC 0-6h regisztrálók orszag eloszlasa', '# Country distribution of UTC 0-6h registrants'),
    @('print(f"\n  UTC 0-6h regisztrálók (n={len(night_signups):,}):")', 'print(f"\n  UTC 0-6h registrants (n={len(night_signups):,}):")'),
    @('print(f"\n  UTC 9-17h regisztrálók (n={len(day_signups):,}):")', 'print(f"\n  UTC 9-17h registrants (n={len(day_signups):,}):")'),
    @('# Agent Builderek kredit tullépés aranya = upgrade potential', '# Agent Builder credit overage rate = upgrade potential'),
    @('print(f"    Agent Builder kredit tullépés: {ab[''had_credit_exceeded''].mean()*100:.1f}%")', 'print(f"    Agent Builder credit overage: {ab[''had_credit_exceeded''].mean()*100:.1f}%")'),
    @('print(f"    Ghost kredit tullépés:         {feat[feat[''segment'']==''Ghost''][''had_credit_exceeded''].mean()*100:.1f}%")', 'print(f"    Ghost credit overage:          {feat[feat[''segment'']==''Ghost''][''had_credit_exceeded''].mean()*100:.1f}%")'),
    @('print(f"    --> Agent Builderek {ab[''had_credit_exceeded''].mean() / max(feat[feat[''segment'']==''Ghost''][''had_credit_exceeded''].mean(), 0.001):.0f}x valoszinubb hogy kreditproblémajuk van")', 'print(f"    --> Agent Builders are {ab[''had_credit_exceeded''].mean() / max(feat[feat[''segment'']==''Ghost''][''had_credit_exceeded''].mean(), 0.001):.0f}x more likely to have credit issues")'),
    @('"Avg aktiv napok"', '"Avg active days"'),
    @('"Kredit tullépés %"', '"Credit overage %"'),
    @('KET ELEMZES:', 'TWO ANALYSES:'),
    @('India hipotezis validalas', 'India hypothesis validation'),
    @('Siker definicio argumentacio', 'Success definition argumentation'),
    @('INDIA HIPOTEZIS VALIDALAS', 'INDIA HYPOTHESIS VALIDATION'),
    @('Hipotezis', 'Hypothesis'),
    @('Validalas', 'Validation'),
    @('orszag', 'country'),
    @('Normalizalas', 'Normalization'),
    @('Orszagonkent', 'By country'),
    @('SIKER DEFINICIO ARGUMENTACIO', 'SUCCESS DEFINITION ARGUMENTATION'),
    @('Szegmens', 'Segment'),
    @('kulonul', 'separate'),
    @('Uzleti ertek', 'Business value'),
    @('Alternativ', 'Alternative'),
    @('definicio', 'definition')
)

Apply-Replacements (Join-Path $base '09_fleet_cohort_model.py') @(
    @('Lokálisan: sequentialis, de ugyanaz a logika.', 'Locally: sequential, but the logic is the same.'),
    @('KERDES: Valtozik-e az ami megjósolja az Agent Builder-re', 'QUESTION: Does what predicts becoming an Agent Builder'),
    @('"<sup>Mennyire jósolható meg az Agent Builder-re valas kohorszonkent?</sup>"', '"<sup>How predictable is becoming an Agent Builder by cohort?</sup>"'),
    @('"<sup>Ugyanazok a factorok jósolnak szeptemberben es decemberben?</sup>"', '"<sup>Do the same factors predict in September and December?</sup>"'),
    @('Fleet-stilus Kohorsz Modell', 'Fleet-style Cohort Model'),
    @('Zerve-n ez Fleet-tel futna:', 'On Zerve this would run with Fleet:'),
    @('osszehasonlitas', 'comparison'),
    @('Lok', 'Locally'),
    @('KERDES', 'QUESTION'),
    @('Korai jelzok', 'Early signals'),
    @('Kohorszok', 'Cohorts'),
    @('FLEET LOGIKA', 'FLEET LOGIC'),
    @('Modellezes', 'Modeling'),
    @('tul keves Agent Builder', 'too few Agent Builders'),
    @('VIZUALIZACIOK', 'VISUALIZATIONS'),
    @('kohorszonkent', 'by cohort'),
    @('kuszob', 'threshold'),
    @('valtoznak-e', 'do they change'),
    @('Osszes user', 'Total users'),
    @('OSSZEFOGLALO', 'SUMMARY'),
    @('Eredmenyek', 'Results'),
    @('megjegyzes', 'note')
)

Apply-Replacements (Join-Path $base '10_user_lifecycle.py') @(
    @('# Signup ideje userenként -- sign_up event VAGY elso event (fallback)', '# Signup time per user -- sign_up event OR first event (fallback)'),
    @('# 3. build call ideje userenként', '# Time of the 3rd build call per user'),
    @('# Index tipusok egységesítése', '# Standardize index types'),
    @('"<sup>A regi kohorszoknak tobb idejuk volt Agent Builderré valni</sup>"', '"<sup>Older cohorts had more time to become Agent Builders</sup>"'),
    @('print("  Mi tortenik az elso 48 oraban ami megjósolja az AB-va valast?")', 'print("  What happens in the first 48 hours that predicts becoming an AB?")'),
    @('# Elso N esemeny per user (kategoriaként)', '# First N events per user (as categories)'),
    @('# Deduplikálás: egymás utani azonos kategoriakat osszevonjuk', '# Deduplication: merge consecutive identical categories'),
    @('# Chart C1: Sankey-jellegű lépés összehasonlítás', '# Chart C1: Sankey-style step comparison'),
    @('subplot_titles=["1. Lepés", "2. Lepés", "3. Lepés"]', 'subplot_titles=["1. Step", "2. Step", "3. Step"]'),
    @('User Eletut & Activation Elemzes', 'User Lifecycle & Activation Analysis'),
    @('HAROM ELEMZES:', 'THREE ANALYSES:'),
    @('Mikor', 'When'),
    @('Mennyi ido', 'How much time'),
    @('magyarázza', 'explains'),
    @('Milestone-ok', 'Milestones'),
    @('utvonal', 'path'),
    @('Szegmens info visszacsatolasa a raw df-be', 'Merge segment info back into the raw dataframe'),
    @('userenk', 'per user'),
    @('elso event', 'first event'),
    @('Build eventek szama', 'Number of build events'),
    @('statisztikak', 'statistics'),
    @('Vertikalis vonalak', 'Vertical lines'),
    @('Kohorszonkent', 'By cohort'),
    @('tipikus', 'typical'),
    @('Egyszerusitett', 'Simplified'),
    @('Deduplik', 'Deduplicate'),
    @('Lepes', 'Step'),
    @('OSSZEFOGLALO', 'SUMMARY'),
    @('Osszefoglalo', 'Summary'),
    @('Legerosebb', 'Strongest')
)

Apply-Replacements (Join-Path $base '11_tool_sequences_session_progression.py') @(
    @('# Userenként tool szekvencia', '# Tool sequence per user'),
    @('# Bigrams szegmensenként', '# Bigrams by segment'),
    @('print("\n  Top bigram tool patok szegmensenként:")', 'print("\n  Top bigram tool paths by segment:")'),
    @('# Chart A2: Tool usage osszetétele szegmensenként', '# Chart A2: Tool usage composition by segment'),
    @('print("  (A backend agent tool eventeknél nincs prop_$session_id)")', 'print("  (Backend agent tool events do not have prop_$session_id)")'),
    @('# Userenként idorendbe rakjuk a tool eventeket', '# Put tool events in chronological order per user'),
    @('# Gap kiszamitasa userenként', '# Calculate gaps per user'),
    @('# Session sorszam userenként', '# Session number per user'),
    @('KET ELEMZES:', 'TWO ANALYSES:'),
    @('normalizalas', 'normalization'),
    @('Csak agent tool eventek', 'Only agent tool events'),
    @('rovid', 'short'),
    @('Userenk', 'Per-user'),
    @('szegmensenk', 'by segment'),
    @('Buildernel', 'among Agent Builders'),
    @('Normalizalas', 'Normalization'),
    @('Idoablak-alapu', 'Time-window-based'),
    @('uj session', 'new session'),
    @('kiszamitasa', 'calculation'),
    @('sorszam', 'number'),
    @('metrikak', 'metrics'),
    @('Progresszio', 'Progression'),
    @('idotartam', 'duration'),
    @('OSSZEFOGLALO', 'SUMMARY'),
    @('Osszefoglalo', 'Summary')
)

Apply-Replacements (Join-Path $base '12_credit_error_propensity.py') @(
    @('print("\n  Credit burn rate szegmensenként:")', 'print("\n  Credit burn rate by segment:")'),
    @('# Chart A1: Burn rate eloszlas szegmensenként', '# Chart A1: Burn rate distribution by segment'),
    @('# Chart B1: Error assist vs nem -- szegmens osszetétel', '# Chart B1: Error assist vs no error assist -- segment composition'),
    @('HAROM ELEMZES:', 'THREE ANALYSES:'),
    @('elkotelezettebb', 'more engaged'),
    @('hipotezis', 'hypothesis'),
    @('confounding-ot', 'confounding'),
    @('CAUSALIS', 'CAUSAL'),
    @('hatterrel', 'background'),
    @('Elemzes', 'Analysis'),
    @('Burn rate = kredit event / aktiv nap', 'Burn rate = credit events / active day'),
    @('szegmensenk', 'by segment'),
    @('kapcsolata', 'relationship'),
    @('hasznalok', 'users'),
    @('Nem hasznalt', 'Did not use'),
    @('Hasznalt', 'Used'),
    @('ora', 'hours'),
    @('osszet', 'composition'),
    @('Kerdes', 'Question'),
    @('Kontrollvaltozok', 'Control variables'),
    @('becslese', 'estimation'),
    @('eloszlas', 'distribution'),
    @('egyszerusitett', 'simplified'),
    @('Matched parok', 'Matched pairs'),
    @('kezelt', 'treated'),
    @('Ellenorzo', 'Check'),
    @('elott', 'before'),
    @('utan', 'after'),
    @('vizualizacio', 'visualization'),
    @('kontroll', 'control'),
    @('Tul keves matched par', 'Too few matched pairs')
)
